import Footer from "@/components/Footer";
import Header from "@/components/Header";
import QueryProvider from "@/providers/QueryProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <QueryProvider>
          <Header />
          <div className="grow-0">{children}</div>

          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
